/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'userId' : string,
  'storyId' : bigint,
  'timestamp' : Time,
}
export interface Logo { 'contentType' : string, 'data' : Uint8Array }
export interface Story {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'thumbnail' : [] | [Logo],
  'timestamp' : Time,
  'excerpt' : string,
  'category' : StoryCategory,
  'youtubeUrl' : [] | [string],
}
export type StoryCategory = { 'trueStories' : null } |
  { 'indianHorror' : null } |
  { 'hauntedPlaces' : null } |
  { 'psychologicalHorror' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], undefined>,
  'addStory' : ActorMethod<
    [string, string, string, StoryCategory, [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteLogo' : ActorMethod<[], undefined>,
  'deleteThumbnail' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getLatestStories' : ActorMethod<[bigint], Array<Story>>,
  'getLogo' : ActorMethod<[], [] | [Logo]>,
  'getStoriesByCategory' : ActorMethod<[StoryCategory], Array<Story>>,
  'getStory' : ActorMethod<[bigint], Story>,
  'getThumbnail' : ActorMethod<[bigint], [] | [Logo]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStories' : ActorMethod<[string], Array<Story>>,
  'toggleNightMode' : ActorMethod<[string, boolean], boolean>,
  'uploadLogo' : ActorMethod<[Uint8Array, string], undefined>,
  'uploadThumbnail' : ActorMethod<[bigint, Uint8Array, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];