/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StoryCategory = IDL.Variant({
  'trueStories' : IDL.Null,
  'indianHorror' : IDL.Null,
  'hauntedPlaces' : IDL.Null,
  'psychologicalHorror' : IDL.Null,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'userId' : IDL.Text,
  'storyId' : IDL.Nat,
  'timestamp' : Time,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
  'excerpt' : IDL.Text,
  'category' : StoryCategory,
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, StoryCategory],
      [IDL.Nat],
      [],
    ),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getLatestStories' : IDL.Func([IDL.Nat], [IDL.Vec(Story)], ['query']),
  'getStoriesByCategory' : IDL.Func(
      [StoryCategory],
      [IDL.Vec(Story)],
      ['query'],
    ),
  'getStory' : IDL.Func([IDL.Nat], [Story], ['query']),
  'searchStories' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
  'toggleNightMode' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StoryCategory = IDL.Variant({
    'trueStories' : IDL.Null,
    'indianHorror' : IDL.Null,
    'hauntedPlaces' : IDL.Null,
    'psychologicalHorror' : IDL.Null,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'userId' : IDL.Text,
    'storyId' : IDL.Nat,
    'timestamp' : Time,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
    'excerpt' : IDL.Text,
    'category' : StoryCategory,
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, StoryCategory],
        [IDL.Nat],
        [],
      ),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getLatestStories' : IDL.Func([IDL.Nat], [IDL.Vec(Story)], ['query']),
    'getStoriesByCategory' : IDL.Func(
        [StoryCategory],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getStory' : IDL.Func([IDL.Nat], [Story], ['query']),
    'searchStories' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
    'toggleNightMode' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };