/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'userId' : string,
  'storyId' : bigint,
  'timestamp' : Time,
}
export interface Story {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : Time,
  'excerpt' : string,
  'category' : StoryCategory,
}
export type StoryCategory = { 'trueStories' : null } |
  { 'indianHorror' : null } |
  { 'hauntedPlaces' : null } |
  { 'psychologicalHorror' : null };
export type Time = bigint;
export interface _SERVICE {
  'addComment' : ActorMethod<[bigint, string, string], undefined>,
  'addStory' : ActorMethod<[string, string, string, StoryCategory], bigint>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getLatestStories' : ActorMethod<[bigint], Array<Story>>,
  'getStoriesByCategory' : ActorMethod<[StoryCategory], Array<Story>>,
  'getStory' : ActorMethod<[bigint], Story>,
  'searchStories' : ActorMethod<[string], Array<Story>>,
  'toggleNightMode' : ActorMethod<[string, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];