/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'userId' : string,
  'storyId' : bigint,
  'timestamp' : Time,
}
export interface Logo { 'contentType' : string, 'data' : Uint8Array }
export interface Story {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : Time,
  'excerpt' : string,
  'category' : StoryCategory,
}
export type StoryCategory = { 'trueStories' : null } |
  { 'indianHorror' : null } |
  { 'hauntedPlaces' : null } |
  { 'psychologicalHorror' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], undefined>,
  'addStory' : ActorMethod<[string, string, string, StoryCategory], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteLogo' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getLatestStories' : ActorMethod<[bigint], Array<Story>>,
  'getLogo' : ActorMethod<[], [] | [Logo]>,
  'getStoriesByCategory' : ActorMethod<[StoryCategory], Array<Story>>,
  'getStory' : ActorMethod<[bigint], Story>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStories' : ActorMethod<[string], Array<Story>>,
  'toggleNightMode' : ActorMethod<[string, boolean], boolean>,
  'uploadLogo' : ActorMethod<[Uint8Array, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];