/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StoryCategory = IDL.Variant({
  'trueStories' : IDL.Null,
  'indianHorror' : IDL.Null,
  'hauntedPlaces' : IDL.Null,
  'psychologicalHorror' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'userId' : IDL.Text,
  'storyId' : IDL.Nat,
  'timestamp' : Time,
});
export const Logo = IDL.Record({
  'contentType' : IDL.Text,
  'data' : IDL.Vec(IDL.Nat8),
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'thumbnail' : IDL.Opt(Logo),
  'timestamp' : Time,
  'excerpt' : IDL.Text,
  'category' : StoryCategory,
  'youtubeUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, StoryCategory, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLogo' : IDL.Func([], [], []),
  'deleteThumbnail' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getLatestStories' : IDL.Func([IDL.Nat], [IDL.Vec(Story)], ['query']),
  'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
  'getStoriesByCategory' : IDL.Func(
      [StoryCategory],
      [IDL.Vec(Story)],
      ['query'],
    ),
  'getStory' : IDL.Func([IDL.Nat], [Story], ['query']),
  'getThumbnail' : IDL.Func([IDL.Nat], [IDL.Opt(Logo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStories' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
  'toggleNightMode' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'uploadLogo' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
  'uploadThumbnail' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat8), IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StoryCategory = IDL.Variant({
    'trueStories' : IDL.Null,
    'indianHorror' : IDL.Null,
    'hauntedPlaces' : IDL.Null,
    'psychologicalHorror' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'userId' : IDL.Text,
    'storyId' : IDL.Nat,
    'timestamp' : Time,
  });
  const Logo = IDL.Record({
    'contentType' : IDL.Text,
    'data' : IDL.Vec(IDL.Nat8),
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'thumbnail' : IDL.Opt(Logo),
    'timestamp' : Time,
    'excerpt' : IDL.Text,
    'category' : StoryCategory,
    'youtubeUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, StoryCategory, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLogo' : IDL.Func([], [], []),
    'deleteThumbnail' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getLatestStories' : IDL.Func([IDL.Nat], [IDL.Vec(Story)], ['query']),
    'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
    'getStoriesByCategory' : IDL.Func(
        [StoryCategory],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getStory' : IDL.Func([IDL.Nat], [Story], ['query']),
    'getThumbnail' : IDL.Func([IDL.Nat], [IDL.Opt(Logo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStories' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
    'toggleNightMode' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'uploadLogo' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
    'uploadThumbnail' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat8), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };