/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Comment {
    content: string;
    userId: string;
    storyId: bigint;
    timestamp: Time;
}
export interface Story {
    id: bigint;
    title: string;
    content: string;
    timestamp: Time;
    excerpt: string;
    category: StoryCategory;
}
export enum StoryCategory {
    trueStories = "trueStories",
    indianHorror = "indianHorror",
    hauntedPlaces = "hauntedPlaces",
    psychologicalHorror = "psychologicalHorror"
}
export interface backendInterface {
    addComment(storyId: bigint, userId: string, content: string): Promise<void>;
    addStory(title: string, excerpt: string, content: string, category: StoryCategory): Promise<bigint>;
    getComments(storyId: bigint): Promise<Array<Comment>>;
    getLatestStories(limit: bigint): Promise<Array<Story>>;
    getStoriesByCategory(category: StoryCategory): Promise<Array<Story>>;
    getStory(id: bigint): Promise<Story>;
    searchStories(queryText: string): Promise<Array<Story>>;
    toggleNightMode(_userId: string, nightModeEnabled: boolean): Promise<boolean>;
}
import type { Story as _Story, StoryCategory as _StoryCategory, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1, arg2);
            return result;
        }
    }
    async addStory(arg0: string, arg1: string, arg2: string, arg3: StoryCategory): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStory(arg0, arg1, arg2, to_candid_StoryCategory_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStory(arg0, arg1, arg2, to_candid_StoryCategory_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getComments(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getLatestStories(arg0: bigint): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestStories(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestStories(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoriesByCategory(arg0: StoryCategory): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoriesByCategory(to_candid_StoryCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoriesByCategory(to_candid_StoryCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStory(arg0: bigint): Promise<Story> {
        if (this.processError) {
            try {
                const result = await this.actor.getStory(arg0);
                return from_candid_Story_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStory(arg0);
            return from_candid_Story_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchStories(arg0: string): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStories(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStories(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleNightMode(arg0: string, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleNightMode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleNightMode(arg0, arg1);
            return result;
        }
    }
}
function from_candid_StoryCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryCategory): StoryCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Story_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Story {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    timestamp: _Time;
    excerpt: string;
    category: _StoryCategory;
}): {
    id: bigint;
    title: string;
    content: string;
    timestamp: Time;
    excerpt: string;
    category: StoryCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        timestamp: value.timestamp,
        excerpt: value.excerpt,
        category: from_candid_StoryCategory_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trueStories: null;
} | {
    indianHorror: null;
} | {
    hauntedPlaces: null;
} | {
    psychologicalHorror: null;
}): StoryCategory {
    return "trueStories" in value ? StoryCategory.trueStories : "indianHorror" in value ? StoryCategory.indianHorror : "hauntedPlaces" in value ? StoryCategory.hauntedPlaces : "psychologicalHorror" in value ? StoryCategory.psychologicalHorror : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Array<Story> {
    return value.map((x)=>from_candid_Story_n4(_uploadFile, _downloadFile, x));
}
function to_candid_StoryCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoryCategory): _StoryCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoryCategory): {
    trueStories: null;
} | {
    indianHorror: null;
} | {
    hauntedPlaces: null;
} | {
    psychologicalHorror: null;
} {
    return value == StoryCategory.trueStories ? {
        trueStories: null
    } : value == StoryCategory.indianHorror ? {
        indianHorror: null
    } : value == StoryCategory.hauntedPlaces ? {
        hauntedPlaces: null
    } : value == StoryCategory.psychologicalHorror ? {
        psychologicalHorror: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
